config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :categories
  resources :products
  resources :homes do 
    collection do
      get :category
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products, :dependent => :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :sub_category
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	has_many :products, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 #before_action :set_category, only: [:edit, :update, :show, :destroy ]
before_action :set_category, except: [:index, :new, :create ]

  def new 
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category created successfully."
      redirect_to categories_path
    else 
      render 'new'
    end
  end

  def index
    @categories = Category.all
  end

  def show
    #@products = Product.searching(params[:id], params[:search])
  end

  def edit
    
  end

  def update
    if @category.update_attributes(category_params)
      flash[:notice] = "Category updated successfully."
      redirect_to categories_path
    else
      render  'edit'
    end
  end


	

  def destroy
    if @category.destroy
      flash[:notice] = "Category deleted successfully."     
      redirect_to admin_categories_path
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    #params.require(:category).permit(:name, :category_show)
        params.require(:category).permit!
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
   @categories = []
   # @categories = Category.all
  end

   def show
   @category = Category.find(params[:id])
   @products = @category.products
 end

def category
	 @categories = Category.where("id = '#{params[:category_id]}'")

    respond_to do |format|
          format.js
      end

end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_product, except: [:index, :new, :create ]

	def new 
		@product = Product.new
	end

	def create
		@product =  Product.new(product_params)
		if @product.save
			flash[:notice] = "product created successfully."
			redirect_to products_path
		else 
			render 'new'
		end
	end

	def index
		@products =  Product.all
	end

	def show

	end

	def edit

	end

	def update
		if @product.update_attributes(product_params)
			flash[:notice] = "product updated successfully."
			redirect_to products_path
		else
			render  'edit'
		end
	end

	def destroy
		if @product.destroy
			flash[:notice] = "product deleted successfully."     
			redirect_to products_path
		end
	end

	private

	def set_product
		@product = Product.find(params[:id])
	end

	def product_params
    #params.require(:product).permit(:name, :product_show)
    params.require(:product).permit!
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
<% if @category.errors.any? %>
  <div class="da-panel-content">
    <div class="da-message warning">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="da-form-row">
  <label><%= f.label :Category_Name %></label>
  <div class="da-form-item large">
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder:"Category Name"%>
    </div>
  </div>

  <div class="da-button-row">
    <%= f.submit class: "da-button blue left" %>
  </div>

  <%end%>

  <%= link_to "Back", categories_path %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render "form" %>

app/views/categories/index.html.erb
<table>
<tr>
<th>CategoryName</th>
<th></th>
</tr>

<% @categories.each do |category| %>
<tr>
<td><%= category.name %></td>
<td><%= link_to "Show", category_path(category), :class => "btn btn-info" %>
<%= link_to "Edit", edit_category_path(category), :class => "btn btn-info" %>
<%= link_to "Delete", category_path(category),  :method => "delete",:data => {:confirm => "are you sure?"}, :class => "btn btn-danger"%>
</td>
<br/>
<%end%>
</tr>
<br/>

<%= link_to "Back", new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>
<%= render "form" %>

app/views/categories/show.html.erb
<%= @category.name %>

<%= link_to "Back", categories_path %>

app/views/homes/_category.html.erb
<%  @categories.each do |category|  %>
  <%= category.name %>
  <% category.products.each do |p| %>
    <%= p.name%>
  <%end%>
<% end %>

app/views/homes/category.js.erb
$("#category1").html('<%= escape_javascript render :partial => "category" %>');

app/views/homes/index.html.erb
<h1>Categories</h1>
<!--% @categories.each do |category|%-->
<!--%= category.name %-->
<!--%end%-->


<!--% @categories.where("name is not null" ).each do |cat| %-->
<!--%= link_to cat.name, home_path(cat) %--><br/>
<!--% cat.products.each do |p|%-->
<!--%= p.name %-->
<!--%= p.price%-->
<!--%= p.description %--><br/>
<!--%end%-->
<!--% end %-->


<%=form_tag root_path do%>

<%=select_tag :category,options_for_select([["select", ""]]+Category.all.map{|i|[i.name,i.id]}), :onchange => "category1(this.value)" %>
<%end%>

<div id="category1">
<%= render :partial => "category" %>
</div>



<script>
  function category1(val){
  var category = val;
 
  $.ajax({
    type: 'GET',
    url: '/homes/category',
    dataType: 'Script',
    data: {
      category_id: category
    },
    success: function(data) {},
  });
  }
</script>

app/views/homes/show.html.erb
home show page	
<% @category.products.each do |cp| %>

<%= cp.name %>
<%= cp.description %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppingcartapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<% if @product.errors.any? %>
  <div class="da-panel-content">
    <div class="da-message warning">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="da-form-row">
  <label>Choose Category</label>
  <div class="da-form-item large">
    <%= f.select :category_id, options_for_select([["Select Category", ""]] + Category.all.map {|c| [c.name, c.id]},:selected => f.object.category_id), {}, :id => "category_id" %>
  </div>
</div>


<div class="da-form-row">
  <label><%= f.label :product_Name %></label>
  <div class="da-form-item large">
    <%= f.text_field :name, class: "form-control", placeholder:"Product Name"%>
    </div>
  </div>


  <div class="da-form-row">
    <label><%= f.label :Description %></label>
    <div class="da-form-item large">
      <%= f.text_area :description,rows: 6, column: 5, class: "form-control ckeditor", placeholder: "Description", :id => "da-ex-elastic" %>
      </div>
    </div>

    <div class="da-form-row">
      <label><%= f.label :price %></label>
      <div class="da-form-item large">
        <%= f.text_field :price , class: "form-control", placeholder: "price" %>
        </div>
      </div>

               
            <div class="da-button-row">
              <%= f.submit class: "da-button blue left" %>
              </div>
<%end%>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render "form" %>

app/views/products/index.html.erb
<table>
<tr>
<th>ProductName</th>
<th>Description</th>
<th>Price</th>
<th>CategoryName</th>
<th></th>


</tr>



<% @products.each do |product| %>
<tr>
<td><%= product.name %></td>
<td><%= product.description %></td>
<td><%= product.price %></td>
<td><%= product.category.name %></td>
<td>
<%= link_to "Show", category_path(product), :class => "btn btn-info" %>
<%= link_to "Edit", edit_category_path(product), :class => "btn btn-info" %>
<%= link_to "Delete", category_path(product),  :method => "delete",:data => {:confirm => "are you sure?"}, :class => "btn btn-danger"%>
</td>
<br/>
</tr>
<%end%>
<br/>
</table>

<%= link_to "Back", new_category_path %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render "form" %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>